#Project Euler Problem 2
#Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
#1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the EVEN-valued terms.
import sys
sys.setrecursionlimit(4000002)


def fib_seq_sum_upto_limit(limit, last_num=2, second_last_num=1, summation=2):
    if last_num > 4000000:
        return summation
    else:
        next_num = (last_num + second_last_num)
        if next_num/2 == next_num/2.0:
            summation += next_num
        return fib_seq_sum_upto_limit(limit, next_num, last_num, summation)
        

print fib_seq_sum_upto_limit(4000000)
